/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique.index'
import { Route as BoutiqueSlugRouteImport } from './routes/boutique.$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueSlugRoute = BoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/boutique': typeof BoutiqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a-propos' | '/contact' | '/boutique/$slug' | '/boutique/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-propos' | '/contact' | '/boutique/$slug' | '/boutique'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/boutique/$slug'
    | '/boutique/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  BoutiqueSlugRoute: typeof BoutiqueSlugRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/boutique'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$slug': {
      id: '/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/boutique/$slug'
      preLoaderRoute: typeof BoutiqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  BoutiqueSlugRoute: BoutiqueSlugRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
